apiVersion: v1
kind: Service
metadata:
  name: product-management-service
spec:
  selector:
    app: product-management-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
